### ISSUE TITLE
compiling on Windows 10 with Qt 5.8

### ISSUE THREAD

**Issue by drhalftone** [jbagg/QtZeroConf#6]
I'm having an impossible time compiling.  The issue seems to the with the keyword "interface" in your QZeroConfService structure.  So I changed the word "interface" to "intrfc" throughout the code, and now I can get it to compile.

struct QZeroConfService {
    QString			name;
    QString			type;
    QString			domain;
    QString			host;
    QHostAddress	ip;
    QHostAddress	ipv6;
    quint32			interface;
    quint16			port;
};

**Comment by jbagg** [comment]
I just pushed a fix.  Can you try it?

**Comment by drhalftone** [comment]
Compiling on Windows, I get errors that the compiler can’t find any of the bonjour_sdk headers.  So I added that directory to the include and depend paths as shown below; however, that still doesn’t work.  So I replaced the <>s with “”s around the associated header includes.

win32 {
        DEFINES+= BUILDLIBRARY
	DEFINES+= WIN32
	DEFINES+= NDEBUG
	DEFINES+= _WINDOWS
	DEFINES+= _USRDLL
	DEFINES+= MDNS_DEBUGMSGS=0
	DEFINES+= WIN32_LEAN_AND_MEAN
	DEFINES+= USE_TCP_LOOPBACK
	DEFINES+= _CRT_SECURE_NO_DEPRECATE
	DEFINES+= _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1
	DEFINES+= NOT_HAVE_SA_LEN
	QMAKE_CFLAGS+= -I$$PWD/bonjour-sdk
	QMAKE_CXXFLAGS+= -I$$PWD/bonjour-sdk -I$$PWD
	HEADERS+= $$PWD/qzeroconf.h $$PWD/bonjour_p.h
        SOURCES+= $$PWD/bonjour.cpp
	SOURCES+= $$PWD/bonjour-sdk/dnssd_clientlib.c
	SOURCES+= $$PWD/bonjour-sdk/dnssd_clientstub.c
	SOURCES+= $$PWD/bonjour-sdk/dnssd_ipc.c
        INCLUDEPATH += $$PWD/bonjour-sdk
        DEPENDPATH += $$PWD/bonjour-sdk
	LIBS+= -lws2_32 -lwsock32
}

Second, I can compile after making those changes above; however, I don’t get a .lib file that I can then use when compiling in the DLL. So you need to add the following to your qzeroconf.h file:

#ifdef Q_OS_WIN
    #if defined BUILDLIBRARY
     #define TEST_COMMON_DLLSPEC Q_DECL_EXPORT
    #else
     #define TEST_COMMON_DLLSPEC Q_DECL_IMPORT
    #endif
#endif

…

class TEST_COMMON_DLLSPEC QZeroConf : public QObject
{
	Q_OBJECT

friend class QZeroConfPrivate;






On Feb 26, 2017, at 5:46 PM, jbagg <notifications@github.com> wrote:

I just pushed a fix. Can you try it?

**Comment by jbagg** [comment]
Which version of msvc are you using?

**Comment by cameronklein** [comment]
I didn't have an issue with the bonjour includes myself, but the `Q_DECL_EXPORT` / `Q_DECL_IMPORT` stuff is needed.

I'd recommend using something different than `BUILDLIBRARY`, though. That seems generic and if that's defined in another library using this one, the symbols will be exported instead of imported.

The Qt standard seems to be `<LIBRARYNAME>_LIBRARY` so adding: `DEFINES += QTZEROCONF_LIBRARY` to the .pro file and using that in place of `BUILDLIBRARY` above would work. One could assume that `QTZEROCONF_LIBRARY` isn't defined in other projects.

**Comment by drhalftone** [comment]
I’m away from the computer, but I’m pretty sure its VS14 that’s included with the VS Community edition.  I’ll take a look in a few hours when I get back to that machine.





On Feb 27, 2017, at 12:04 PM, jbagg <notifications@github.com <mailto:notifications@github.com>> wrote:

Which version of msvc are you using?

**Comment by jbagg** [comment]
I've added the Q_DECL_EXPORT stuff.  Looks like it is ok on win7-64 using VS14 and Qt 5.6.2.  Downloading Qt 5.8 right now.

**Comment by drhalftone** [comment]
Absolutely love this class! And I greatly appreciate you supporting it. Today, I installed QtZeroConf on my Intel Joule running Ubuntu 16.04 LTS.  May I make the suggestion that you change your installation instructions to read "libavahi-client-dev" and "libavahi-common-dev" because I needed to use these strings with apt-get otherwise apt-get said it couldn’t find the libraries.


On Feb 28, 2017, at 5:28 PM, jbagg <notifications@github.com> wrote:

I've added the Q_DECL_EXPORT stuff. Looks like it is ok on win7-64 using VS14 and Qt 5.6.2. Downloading Qt 5.8 right now.

**Comment by jbagg** [comment]
I am glad you like it and it is of use to you.

I've Tried both Qt 5.6.2 and 5.8 with VS14 in windows 7-64bit and I 
don't get any include issues.  Can you try a fresh source tree?  If you 
still have issues with includes, I'll try and track down a win 10 machine.

**Comment by drhalftone** [comment]
Take a look at this.  It demonstrates using QZeroConf to connect between the Intel Joule on the robot and my laptop.



https://www.youtube.com/watch?v=7rRCKFGvR_M&feature=em-upload_owner#action=share <https://www.youtube.com/watch?v=7rRCKFGvR_M&feature=em-upload_owner#action=share>




On Mar 1, 2017, at 6:27 PM, jbagg <notifications@github.com <mailto:notifications@github.com>> wrote:

I am glad you like it and it is of use to you.

I've Tried both Qt 5.6.2 and 5.8 with VS14 in windows 7-64bit and I 
don't get any include issues. Can you try a fresh source tree? If you 
still have issues with includes, I'll try and track down a win 10 machine.
